preprocess:
  sample_rate: 24000
  preemph: 0.97
  n_mels: 512
  n_fft: 2048
  hop_length: 300
  win_length: 1200
  max_db: 100
  ref_db: 20
  top_db: 15

model:
  ContentEncoder:
    c_in: 512
    c_h: 128
    c_out: 128
    kernel_size: 5
    bank_size: 8
    bank_scale: 1
    c_bank: 128
    n_conv_blocks: 6
    subsample: [1, 2, 1, 2, 1, 2]
    act: "relu"
    dropout_rate: 0
  SpeakerEncoder:
    c_in: 512
    c_h: 128
    c_out: 128
    kernel_size: 5
    bank_size: 8
    bank_scale: 1
    c_bank: 128
    n_conv_blocks: 6
    n_dense_blocks: 6
    subsample: [1, 2, 1, 2, 1, 2]
    act: "relu"
    dropout_rate: 0
  Decoder:
    c_in: 128
    c_cond: 128
    c_h: 128
    c_out: 512
    kernel_size: 5
    n_conv_blocks: 6
    upsample: [2, 1, 2, 1, 2, 1]
    act: "relu"
    sn: False
    dropout_rate: 0
